language: node_js
node_js:
  - 9
  - 8
branches:
  only:
    - master
install:
  - npm install
script:
  - npm run docz:build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: .docz/dist
  on:
    branch: master
